Translation updates; Added debug incremental language switcher; Other minor updates
Pharloom Atlas help file config name translation updates:
	Added translated double quotes around them:
		Files: HelpWindow.cs
		Translation Files: PharloomAtlas/*/*.tr.json,
	They are now translated:
		Files: HelpWindow.cs
		Translation Files (Fixed config name [Highlight Hornet marker] that was accidentally translated): PharloomAtlas/*/{sw,vi,tr}.tr.json

Ran translations back through ChatGPT and adding minor edits:
	Translation Files: SilkDev/.../sw.tr.json, PharloomAtlas/*/{sw,ta}.tr.json

Added note in documentation files that translations were LLM generated:
	Files: *.NextusMods.txt, */README.md

Added debug incremental language switcher:
	Files: SilkDev/.../Config.cs

Other minor updates:
	pre-commit:
		Added UTF8 validity check in githook pre-commit
		Normalized whitespace
	shared:
		Cleaned up MakeZip() function
		Now also outputting zips with no translations

diff --git a/Compile/shared b/Compile/shared
--- a/Compile/shared
+++ b/Compile/shared
@@ -70,13 +70,25 @@ ensure_dir "$plugin_dir" || exit 1
 #Functions used by callers to finish up the job
 MakeZip() {
 	#Compile the zip
-	zip_path="$zip_dir/$1"
+	local zip_path="$zip_dir/$1"
 	rm -f "$zip_path"
 	cp -Lpr "$links_dir/"* "$plugin_dir/"				|| exit_error "Failed to copy $links_dir to $plugin_dir"
 	rm -f "$plugin_dir/$trans_dir/"*"/default.tr.json"
 	zip -r -9 "$zip_path" "${@:2}"						|| exit_error "Zipping failed"
-	7z a -t7z -mx=9 "$zip_dir/${1%.zip}.7z" "${@:2}"
-	#rm -rf "$plugin_dir"
+	#7z a -t7z -mx=9 "$zip_dir/${1%.zip}.7z" "${@:2}"
+
+	#.en zip (exclude Translations params)
+	local en_zip="${zip_path%.zip}.en.zip"
+	local en_args=()
+	shift #Skip $1
+	for arg in "$@"; do
+		[[ ! "$arg" == "$plugin_dir/$trans_dir/"* ]] && en_args+=("$arg")
+	done
+	zip -r -9 "$en_zip" "${en_args[@]}" || exit_error "Zipping .en failed"
+	#7z a -t7z -mx=9 "${en_zip%.zip}.7z" "${en_args[@]}"
+
+	#Cleanup
+	rm -rf "$plugin_dir"
 
 	#Let the user know the results
 	unzip -l "$zip_path"
